version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./posse-app:/var/www/html
    app:
        build: ./php
        image: php:7.4-fpm
        depends_on:
            - db
        volumes:
            - ./posse-app:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports: ["8888:80"]
        depends_on: ["db"]
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: quizy
            MYSQL_USER: mikiharu
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/sql:/docker-entrypoint-initdb.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/
